name: nishali app containerization pipelinbe

#Trigger section
on:
  push:
    branches:
      - "main"

#Jobs
jobs:
  nish-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: run some basic commands on above server to do some verifications
        run: |
          uname -r
          whoami
          cat /etc/os-release
          docker version
          docker-compose version

      - name: using pre-designed github workflow to get copy gitrepo code to runner machine
        uses: actions/checkout@v4

      - name: verify github code
        run: ls -a
      
      - name: verify github code and use docker compose to build and create
        run: |
          ls -a
          docker-compose up -d
          sleep 2
          docker-compose ps 

      - name: verify health.html 
        run: |
          echo "Accessing health.html using curl"
          curl -f http://localhost:1234/health.html