name: nishali app containerization pipelinbe

#Trigger section
on:
  push:
    branches:
      - "dev1"

#Jobs
jobs:
  nish-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: run some basic commands on above server to do some verifications
        run: |
          uname -r
          whoami
          cat /etc/os-release
          docker version
          docker-compose version
          #sonarqube-scanner --version

      - name: using pre-designed github workflow to get copy gitrepo code to runner machine
        uses: actions/checkout@v4

      #- name: SonarQube Scan
      #  uses: sonarsource/sonarqube-scan-action@<action version> # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      #  env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #    SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: verify github code
        run: ls -a
      
      - name: verify github code and use docker compose to build and create
        run: |
          ls -a
          docker-compose up -d
          sleep 2
          docker-compose ps 

      - name: verify health.html 
        run: |
          echo "Accessing health.html using curl"
          curl -f http://localhost:1234/health.html

      - name: try to login from runner to dockerhub account
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: rebuild image in dockerhub format and push it to dockerhub 
        uses: docker/build-push-action@v5
        with:
          context: . #location of docker file
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nishbmo-ui:uiversion001

      - name: logout from docker
        run: docker logout
